# SITE CONFIGURATION
url: "https://balit.ski"
baseurl: "/discremath"
favicon: assets/favicon.ico                             # Icon displayed in the tab

reveal:
  title: "Reveal-jekyll"
  transition: "slide" # none/fade/slide/convex/concave/zoom
  theme: "solarized" # black/beige/blood/league/moon/night/serif/simple/sky/solarized/white
  number: false
  numberType: "c/t" # "c" / "h.v" / "h/v" / "c/t"

# Slides
collections:
  slides:
    output: true
    permalink: /:collection/:name
  basements:
    output: true
    permalink: /:collection/:name
  posts: 
    output: true
    permalink: /:title

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea"]
